import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { BackgroundProvider } from "./contexts/BackgroundContext";

import HeaderBanner from "@/components/shared/header-banner";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Wingman Avtech | Modern apps for everyone in aviation",
  description: "Generated by create next app (to be updated)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
      >
        <BackgroundProvider>
          {/* HEADER BANNER */}
          <HeaderBanner /> {/* Control it using the data file */}
          {/* END HEADER BANNER */}

          {/* NAVBAR */}
          <Navbar />
          {/* END NAVBAR */}
          
          {/* PAGE CONTENTS */}
          {children}
          {/* END PAGE CONTENTS */}

          {/* FOOTER */}
          <Footer />
          {/* END FOOTER */}
        </BackgroundProvider>
      </body>
    </html>
  );
}
