import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { BackgroundProvider } from "./contexts/BackgroundContext";
import ConditionalLayoutComponents from "./ConditionalLayoutComponents";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Wingman Avtech | Modern apps for everyone in aviation",
  description: "Generated by create next app (to be updated)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
      >
        <BackgroundProvider>
          <ConditionalLayoutComponents>
            {children}
          </ConditionalLayoutComponents>
        </BackgroundProvider>
      </body>
    </html>
  );
}
