import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import HeaderBanner from "@/components/shared/header-banner";
import Navbar from "@/components/shared/navbar";
import Footer from "@/components/shared/footer"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Wingman Avtech | Modern apps for everyone in aviation",
  description: "Generated by create next app (to be updated)",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased scroll-smooth`}
      >

        {/* HEADER BANNER */}
        <HeaderBanner
            title="Announcement:"
            message="AirRoster v2.0.7 is now live. We now support 80+ airlines around the 🌏"
            buttonText="Learn more"
            buttonHref="/announcements/airroster-2-0-7-is-live"
            bgColor="bg-blue-600"                    
        />
        {/* END HEADER BANNER */}


        {/* NAVBAR */}
        <Navbar />
        {/* END NAVBAR */}
        

        {/* PAGE CONTENTS */}
        {children}
        {/* END PAGE CONTENTS */}

        {/* FOOTER */}
        <Footer />
        {/* END FOOTER */}
      </body>
    </html>
  );
}
